#ifndef RELATION_OPTICS_EDIT_CONTROLLER_H
#define RELATION_OPTICS_EDIT_CONTROLLER_H
#include "relation_cde90_window_export.h"
_R_WINDOW(RelationOpticsEditController)
#endif //RELATION_OPTICS_EDIT_CONTROLLER_H
