sql.host=39.98.45.96
sql.port=3306
sql.username=shisan
sql.password=xss_332211.
; sql.type=QPSQL
; sql.host=192.168.31.143
; sql.port=5432
; sql.username=postgres
; sql.password=hengren08
sql.initSize=1
sql.maxSize=10
sql.testTimeout=60
sql.testSql=select 'x'
sql.database=cd_sem
sql.file.database=cd_sem_file
sql.auth.database=cd_sem_auth
sql.log.database=cd_sem_log

#在测试环境，可通过该配置覆盖数据库中的zeiss server配置
__zeiss_server=192.168.31.180:10001
__hardware_server_host=192.168.31.180:10002
__OM_TYPE=DEBUG