#ifndef UI_IDP_CREATION_GLOBAL_H
#define UI_IDP_CREATION_GLOBAL_H
#include <QtGlobal>
#ifdef UI_IDP_CREATION_GLOBAL_LIB
#define UI_IDP_CREATION_EXPORT Q_DECL_EXPORT
#else
#define UI_IDP_CREATION_EXPORT Q_DECL_IMPORT
#endif
#endif // UI_IDP_CREATION_GLOBAL_H
