//
// Created by Shisan on 2026/3/17.
//

#ifndef HENGREN_CD_SEM_LOG_VIEWER_SIGNAL_BRIDGE_H
#define HENGREN_CD_SEM_LOG_VIEWER_SIGNAL_BRIDGE_H


#ifdef __LOG_VIEWER__TARGET
#include "signal_hub_plugin_concat.h"
#include "log_view_global.h"
SIGNAL_EXPORT LOG_VIEW_LIB_EXPORT SIGNAL_CHECK(__LOG_VIEWER__TARGET);
SIGNAL_EXPORT LOG_VIEW_LIB_EXPORT SIGNAL_REG(__LOG_VIEWER__TARGET);
SIGNAL_EXPORT LOG_VIEW_LIB_EXPORT SIGNAL_UNREG(__LOG_VIEWER__TARGET);
#endif


#endif //HENGREN_CD_SEM_LOG_VIEWER_SIGNAL_BRIDGE_H