#ifndef UI_WORKSHEET_CREATION_GLOBAL_H
#define UI_WORKSHEET_CREATION_GLOBAL_H
#include <QtGlobal>
#ifdef UI_WORKSHEET_GLOBAL_LIB
#define UI_WORKSHEET_EXPORT Q_DECL_EXPORT
#else
#define UI_WORKSHEET_EXPORT Q_DECL_IMPORT
#endif
#endif // UI_WORKSHEET_CREATION_GLOBAL_H
