#ifndef WORKSHEET_SIGNAL_BRIDGE_H
#define WORKSHEET_SIGNAL_BRIDGE_H

#ifdef __WORKSHEET_TARGET
#include "signal_hub_plugin_concat.h"
#include "ui_worksheet_creation_global.h"
SIGNAL_EXPORT UI_WORKSHEET_EXPORT SIGNAL_CHECK(__WORKSHEET_TARGET);
SIGNAL_EXPORT UI_WORKSHEET_EXPORT SIGNAL_REG(__WORKSHEET_TARGET);
SIGNAL_EXPORT UI_WORKSHEET_EXPORT SIGNAL_UNREG(__WORKSHEET_TARGET);
#endif


#endif // WORKSHEET_SIGNAL_BRIDGE_H
