#ifndef IMAGE_OPERATION_SIGNAL_BRIDGE_H
#define IMAGE_OPERATION_SIGNAL_BRIDGE_H

#ifdef _IMAGE_OPERATION_TARGET
#include "signal_hub_plugin_concat.h"
#include "ui_image_operation_global.h"
SIGNAL_EXPORT UI_IMAGE_OPERATION_EXPORT SIGNAL_CHECK(_IMAGE_OPERATION_TARGET);
SIGNAL_EXPORT UI_IMAGE_OPERATION_EXPORT SIGNAL_REG(_IMAGE_OPERATION_TARGET);
SIGNAL_EXPORT UI_IMAGE_OPERATION_EXPORT SIGNAL_UNREG(_IMAGE_OPERATION_TARGET);
#endif


#endif //IMAGE_OPERATION_SIGNAL_BRIDGE_H
