#ifndef UI_IMAGE_OPERATION_GLOBAL_H
#define UI_IMAGE_OPERATION_GLOBAL_H
#include <QtGlobal>
#ifdef UI_IMAGE_OPERATION_GLOBAL_LIB
#define UI_IMAGE_OPERATION_EXPORT Q_DECL_EXPORT
#else
#define UI_IMAGE_OPERATION_EXPORT Q_DECL_IMPORT
#endif

#endif // UI_IMAGE_OPERATION_GLOBAL_H
