#ifndef UI_RECIPE_CREATION_GLOBAL_H
#define UI_RECIPE_CREATION_GLOBAL_H
#include <QtGlobal>
#ifdef UI_RECIPE_CREATION_GLOBAL_LIB
#define UI_RECIPE_LIB_DEP Q_DECL_EXPORT
#else
#define UI_RECIPE_LIB_DEP Q_DECL_IMPORT
#endif
#endif // UI_RECIPE_CREATION_GLOBAL_H
