#ifndef UI_COMMON_GLOBAL_H
#define UI_COMMON_GLOBAL_H
#include <QtGlobal>

#ifdef UI_COMMON_GLOBAL_LIB
#define UI_COMMON_EXPORT Q_DECL_EXPORT
#else
#define UI_COMMON_EXPORT Q_DECL_IMPORT
#endif

#endif // UI_COMMON_GLOBAL_H
