#ifndef UI_JOB_CREATION_GLOBAL_H
#define UI_JOB_CREATION_GLOBAL_H
#include <QtGlobal>
#ifdef UI_JOB_CREATION_GLOBAL_LIB
#define UI_JOB_LIB_EXPORT Q_DECL_EXPORT
#else
#define UI_JOB_LIB_EXPORT Q_DECL_IMPORT
#endif
#endif // UI_JOB_CREATION_GLOBAL_H
