#ifndef CDSEM_PLUGIN_MSR_EXPORT_GLOBAL_H
#define CDSEM_PLUGIN_MSR_EXPORT_GLOBAL_H
#include <QtGlobal>
#ifdef CDSEM_PLUGIN_MSR_EXPORT_GLOBAL
#define CDSEM_PLUGIN_MSR_EXPORT Q_DECL_EXPORT
#else
#define CDSEM_PLUGIN_MSR_EXPORT Q_DECL_IMPORT
#endif
#endif // CDSEM_MSR_EXPORT_PLUGIN_GLOBAL_H
