#ifndef XLSX_EXPORT_SIGNAL_BRIDGE_H
#define XLSX_EXPORT_SIGNAL_BRIDGE_H

#ifdef _XLSX_EXP_TARGET
#include "signal_hub_plugin_concat.h"
#include "cdsem_plugin_msr_export_global.h"
SIGNAL_EXPORT CDSEM_PLUGIN_MSR_EXPORT SIGNAL_CHECK(_XLSX_EXP_TARGET);
SIGNAL_EXPORT CDSEM_PLUGIN_MSR_EXPORT SIGNAL_REG(_XLSX_EXP_TARGET);
SIGNAL_EXPORT CDSEM_PLUGIN_MSR_EXPORT SIGNAL_UNREG(_XLSX_EXP_TARGET);
#endif

#endif // XLSX_EXPORT_SIGNAL_BRIDGE_H
