#ifndef UI_SINGLE_MAIN_GLOBAL_H
#define UI_SINGLE_MAIN_GLOBAL_H
#include <QtGlobal>
#ifdef UI_CONTROL_PANE_GLOBAL_LIB
#define UI_CONTROL_PANE_EXPORT Q_DECL_EXPORT
#else
#define UI_CONTROL_PANE_EXPORT Q_DECL_IMPORT
#endif

#endif // UI_SINGLE_MAIN_GLOBAL_H
