#ifndef CONTROL_PANE_SIGNALS_BRIDGE_H
#define CONTROL_PANE_SIGNALS_BRIDGE_H
#ifdef __CONTROL_PANE_TARGET
#include "signal_hub_plugin_concat.h"
#include "control_pane_global.h"
SIGNAL_EXPORT UI_CONTROL_PANE_EXPORT SIGNAL_CHECK(__CONTROL_PANE_TARGET);
SIGNAL_EXPORT UI_CONTROL_PANE_EXPORT SIGNAL_REG(__CONTROL_PANE_TARGET);
SIGNAL_EXPORT UI_CONTROL_PANE_EXPORT SIGNAL_UNREG(__CONTROL_PANE_TARGET);
#endif

#endif // CONTROL_PANE_SIGNALS_BRIDGE_H
