#ifndef IMAGE_MANAGER_SIGNAL_BRIDGE_H
#define IMAGE_MANAGER_SIGNAL_BRIDGE_H

#ifdef __IMAGE_MANAGER_TARGET
#include "signal_hub_plugin_concat.h"
#include "ui_image_manager_global.h"
SIGNAL_EXPORT UI_IMG_MANAGER_EXPORT SIGNAL_CHECK(__IMAGE_MANAGER_TARGET);
SIGNAL_EXPORT UI_IMG_MANAGER_EXPORT SIGNAL_REG(__IMAGE_MANAGER_TARGET);
SIGNAL_EXPORT UI_IMG_MANAGER_EXPORT SIGNAL_UNREG(__IMAGE_MANAGER_TARGET);
#endif

#endif // IMAGE_MANAGER_SIGNAL_BRIDGE_H
