#ifndef UI_IMAGE_MANAGER_GLOBAL_H
#define UI_IMAGE_MANAGER_GLOBAL_H

#include <QtGlobal>

#ifdef UI_IMG_MANAGER_GLOBAL_LIB
#define UI_IMG_MANAGER_EXPORT Q_DECL_EXPORT
#else
#define UI_IMG_MANAGER_EXPORT Q_DECL_IMPORT
#endif
#endif // UI_IMAGE_MANAGER_GLOBAL_H
