#ifndef AMP_SIGNAL_BRIDGE_H
#define AMP_SIGNAL_BRIDGE_H

#ifdef _AMP_TARGET
#include "signal_hub_plugin_concat.h"
#include "ui_amp_operation_global.h"
SIGNAL_EXPORT UI_AMP_OPERATION_EXPORT SIGNAL_CHECK(_AMP_TARGET);
SIGNAL_EXPORT UI_AMP_OPERATION_EXPORT SIGNAL_REG(_AMP_TARGET);
SIGNAL_EXPORT UI_AMP_OPERATION_EXPORT SIGNAL_UNREG(_AMP_TARGET);
#endif

#endif // AMP_SIGNAL_BRIDGE_H
