#ifndef UI_AMP_OPERATION_GLOBAL_H
#define UI_AMP_OPERATION_GLOBAL_H
#include <QtGlobal>
#ifdef UI_AMP_OPERATION_GLOBAL_LIB
#define UI_AMP_OPERATION_EXPORT Q_DECL_EXPORT
#else
#define UI_AMP_OPERATION_EXPORT Q_DECL_IMPORT
#endif
#endif // UI_AMP_OPERATION_GLOBAL_H
