#ifndef PROCEDURE_MANUAL_GLOBAL_H
#define PROCEDURE_MANUAL_GLOBAL_H
#include <QtGlobal>
#ifdef UI_PROCEDURE_MANUAL_LIB
#define UI_PROCEDURE_MANUAL_EXPORT Q_DECL_EXPORT
#else
#define UI_PROCEDURE_MANUAL_EXPORT Q_DECL_IMPORT
#endif

#endif // PROCEDURE_MANUAL_GLOBAL_H
