#ifndef DATA_MANAGER_SIGNAL_BRIDGE_H
#define DATA_MANAGER_SIGNAL_BRIDGE_H

#ifdef __DATA_MANAGER_TARGET
#include "signal_hub_plugin_concat.h"
#include "ui_data_manager_creation_global.h"
SIGNAL_EXPORT UI_DATA_MANAGER_EXPORT SIGNAL_CHECK(__DATA_MANAGER_TARGET);
SIGNAL_EXPORT UI_DATA_MANAGER_EXPORT SIGNAL_REG(__DATA_MANAGER_TARGET);
SIGNAL_EXPORT UI_DATA_MANAGER_EXPORT SIGNAL_UNREG(__DATA_MANAGER_TARGET);
#endif

#endif // DATA_MANAGER_SIGNAL_BRIDGE_H
