#ifndef UI_DATA_MANAGER_CREATION_GLOBAL_H
#define UI_DATA_MANAGER_CREATION_GLOBAL_H
#include <QtGlobal>
#ifdef UI_DATA_MANAGER_CREATION_GLOBAL_LIB
#define UI_DATA_MANAGER_EXPORT Q_DECL_EXPORT
#else
#define UI_DATA_MANAGER_EXPORT Q_DECL_IMPORT
#endif
#endif // UI_DATA_MANAGER_CREATION_GLOBAL_H
